version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      #- esvolume:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    mem_limit: 1g
    ports: 
      - "5601:5601"
    volumes: 
      - "./config/kibana.yml:/usr/share/kibana/config/kibana.yml"
    environment:
      - "xpack.security.enabled=false"
    depends_on: 
      - elasticsearch

# volumes:
#   esvolume:
#     driver: local